<?php

namespace Yoda\EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
  public function getUpcomingEvents($max = null) {
      $qb = $this
        ->createQueryBuilder('e')
        ->addORderBy('e.time', 'ASC')
        ->andWhere('e.time > :now')
        ->setParameter('now', new \DateTime());

     if($max) {
       $qb->setMaxResults($max);
     }

     return $qb
        ->getQuery()
        ->execute()
      ;
  }

  /**
   * @return Event[]
   */
  public function getRecentlyUpdatedEvents() {
    return $this
        ->createQueryBuilder('e')
        ->andWhere('e.updatedAt > :since')
        ->setParameter('since', new \DateTime('24 hours ago'))
        ->getQuery()
        ->execute()
        ;
  }
}
